AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates a Platform9 IAM user & Access Key, creates & attaches required IAM policies for EMP and outputs access Key ID & Secret for the Platform9 IAM user'
Parameters:
  IAMUserName:
    Type: String
    Default: 'platform9-emp-user'
    Description: '(Required) IAM User Name created for EMP'
  S3BucketPrefix:
    Type: String
    Default: 'emp-loki'
    Description: '(Required) S3 Bucket Name Prefix for EMP Log Management'
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub:
        - "${BucketNamePrefix}-${AccountIdSuffix}"
        - BucketNamePrefix: !Ref S3BucketPrefix
          AccountIdSuffix: !Ref AWS::AccountId
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
  IAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref IAMUserName
  IAMAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref IAMUser
  Policy1:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: Platform9EMPCustomPolicy01
      Description: 'Part 1 of required policies for Platform9 EMP'
      Users:
      - !Ref IAMUser
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - ec2:AllocateAddress
          - ec2:AssociateRouteTable
          - ec2:AttachInternetGateway
          - ec2:AuthorizeSecurityGroupEgress
          - ec2:AuthorizeSecurityGroupIngress
          - ec2:CreateInternetGateway
          - ec2:CreateNatGateway
          - ec2:CreateRoute
          - ec2:CreateRouteTable
          - ec2:CreateSecurityGroup
          - ec2:CreateSubnet
          - ec2:CreateVpc
          - ec2:CreateTags
          - ec2:DeleteInternetGateway
          - ec2:DeleteNatGateway
          - ec2:DeleteRoute
          - ec2:DeleteRouteTable
          - ec2:DeleteSecurityGroup
          - ec2:DeleteSubnet
          - ec2:DeleteTags
          - ec2:DeleteVpc
          - ec2:DescribeAccountAttributes
          - ec2:DescribeAddresses
          - ec2:DescribeAvailabilityZones
          - ec2:DescribeImages
          - ec2:DescribeInstances
          - ec2:DescribeInternetGateways
          - ec2:DescribeKeyPairs
          - ec2:DescribeNatGateways
          - ec2:DescribeNetworkAcls
          - ec2:DescribeNetworkInterfaces
          - ec2:DescribeRegions
          - ec2:DescribeRouteTables
          - ec2:DescribeSubnets
          - ec2:DescribeVpcAttribute
          - ec2:DescribeVpcClassicLink
          - ec2:DescribeVpcClassicLinkDnsSupport
          - ec2:DescribeVpcs
          - ec2:DescribeTags
          - ec2:DetachInternetGateway
          - ec2:DisassociateRouteTable
          - ec2:ImportKeyPair
          - ec2:ModifySubnetAttribute
          - ec2:ModifyVpcAttribute
          - ec2:ReleaseAddress
          - ec2:ReplaceRouteTableAssociation
          - ec2:RevokeSecurityGroupEgress
          - ec2:RevokeSecurityGroupIngress
          - ec2:RunInstances
          - ec2:TerminateInstances
          - ec2:DescribeInstanceTypes
          - ec2:DescribeSecurityGroups
          - ec2:DescribeSecurityGroupRules
          - ec2:ModifyInstanceMetadataOptions
          - ec2:ModifySecurityGroupRules
          - ec2:UpdateSecurityGroupRuleDescriptionsEgress
          - ec2:UpdateSecurityGroupRuleDescriptionsIngress
          - ec2:AcceptVpcPeeringConnection
          - ec2:CreateVpcPeeringConnection
          - ec2:DeleteVpcPeeringConnection
          - ec2:DescribeVpcPeeringConnections
          - ec2:ModifyVpcPeeringConnectionOptions
          - ec2:RejectVpcPeeringConnection
          - ec2:DescribeVolumes
          - ec2:DescribeVolumesModifications
          - ec2:AssignPrivateIpAddresses
          - ec2:AttachNetworkInterface
          - ec2:CreateNetworkInterface
          - ec2:DeleteNetworkInterface
          - ec2:DetachNetworkInterface
          - ec2:ModifyNetworkInterfaceAttribute
          - ec2:UnassignPrivateIpAddresses
          - ec2:AttachVolume
          - ec2:CreateVolume
          - ec2:DeleteVolume
          - ec2:DescribeDhcpOptions
          - ec2:DetachVolume
          - ec2:ModifyInstanceAttribute
          - ec2:ModifyVolume
          - eks:AccessKubernetesApi
          - eks:DescribeAddon
          - eks:DescribeAddonVersions
          - eks:DescribeCluster
          - eks:DescribeFargateProfile
          - eks:DescribeIdentityProviderConfig
          - eks:DescribeNodegroup
          - eks:DescribeUpdate
          - eks:ListAddons
          - eks:ListClusters
          - eks:ListFargateProfiles
          - eks:ListIdentityProviderConfigs
          - eks:ListNodegroups
          - eks:ListTagsForResource
          - eks:ListUpdates
          - eks:CreateNodegroup
          - autoscaling:AttachLoadBalancers
          - autoscaling:CreateAutoScalingGroup
          - autoscaling:CreateLaunchConfiguration
          - autoscaling:CreateOrUpdateTags
          - autoscaling:DeleteAutoScalingGroup
          - autoscaling:DeleteLaunchConfiguration
          - autoscaling:DeleteTags
          - autoscaling:DescribeAutoScalingGroups
          - autoscaling:DescribeLaunchConfigurations
          - autoscaling:DescribeLoadBalancers
          - autoscaling:DescribeScalingActivities
          - autoscaling:DetachLoadBalancers
          - autoscaling:EnableMetricsCollection
          - autoscaling:ResumeProcesses
          - autoscaling:SuspendProcesses
          - autoscaling:UpdateAutoScalingGroup
          - autoscaling:DescribeAutoScalingInstances
          - autoscaling:SetDesiredCapacity
          - autoscaling:SetInstanceProtection
          Resource: "*"
        - Effect: Allow
          Action:
          - ec2:CreateNetworkInterfacePermission
          Resource: "*"
          Condition:
            ForAnyValue:StringEquals:
              "ec2:ResourceTag/eks:eni:owner": "eks-vpc-resource-controller"
  Policy2:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: Platform9EMPCustomPolicy02
      Description: 'Part 2 of required policies for Platform9 EMP'
      Users:
      - !Ref IAMUser
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - elasticloadbalancing:AddTags
          - elasticloadbalancing:ApplySecurityGroupsToLoadBalancer
          - elasticloadbalancing:AttachLoadBalancerToSubnets
          - elasticloadbalancing:ConfigureHealthCheck
          - elasticloadbalancing:CreateLoadBalancer
          - elasticloadbalancing:CreateLoadBalancerListeners
          - elasticloadbalancing:DeleteLoadBalancer
          - elasticloadbalancing:DescribeInstanceHealth
          - elasticloadbalancing:DescribeLoadBalancerAttributes
          - elasticloadbalancing:DescribeTags
          - elasticloadbalancing:ModifyLoadBalancerAttributes
          - elasticloadbalancing:RemoveTags
          - elasticloadbalancing:CreateListener
          - elasticloadbalancing:CreateLoadBalancerPolicy
          - elasticloadbalancing:CreateTargetGroup
          - elasticloadbalancing:DeleteListener
          - elasticloadbalancing:DeleteLoadBalancerListeners
          - elasticloadbalancing:DeleteTargetGroup
          - elasticloadbalancing:DeregisterInstancesFromLoadBalancer
          - elasticloadbalancing:DeregisterTargets
          - elasticloadbalancing:DescribeListeners
          - elasticloadbalancing:DescribeLoadBalancerPolicies
          - elasticloadbalancing:DescribeLoadBalancers
          - elasticloadbalancing:DescribeTargetGroupAttributes
          - elasticloadbalancing:DescribeTargetGroups
          - elasticloadbalancing:DescribeTargetHealth
          - elasticloadbalancing:DetachLoadBalancerFromSubnets
          - elasticloadbalancing:ModifyListener
          - elasticloadbalancing:ModifyTargetGroup
          - elasticloadbalancing:ModifyTargetGroupAttributes
          - elasticloadbalancing:RegisterInstancesWithLoadBalancer
          - elasticloadbalancing:RegisterTargets
          - elasticloadbalancing:SetLoadBalancerPoliciesForBackendServer
          - elasticloadbalancing:SetLoadBalancerPoliciesOfListener
          - iam:AddRoleToInstanceProfile
          - iam:CreateInstanceProfile
          - iam:CreateRole
          - iam:CreateServiceLinkedRole
          - iam:DeleteInstanceProfile
          - iam:DeleteRole
          - iam:DeleteRolePolicy
          - iam:GetInstanceProfile
          - iam:GetRole
          - iam:GetRolePolicy
          - iam:GetUser
          - iam:ListAttachedRolePolicies
          - iam:ListInstanceProfilesForRole
          - iam:ListRolePolicies
          - iam:PassRole
          - iam:PutRolePolicy
          - iam:RemoveRoleFromInstanceProfile
          - elasticfilesystem:Backup
          - elasticfilesystem:CreateAccessPoint
          - elasticfilesystem:CreateFileSystem
          - elasticfilesystem:CreateMountTarget
          - elasticfilesystem:CreateTags
          - elasticfilesystem:DeleteAccessPoint
          - elasticfilesystem:DeleteFileSystem
          - elasticfilesystem:DeleteMountTarget
          - elasticfilesystem:DeleteTags
          - elasticfilesystem:DescribeAccessPoints
          - elasticfilesystem:DescribeFileSystems
          - elasticfilesystem:DescribeMountTargets
          - elasticfilesystem:DescribeTags
          - elasticfilesystem:ListTagsForResource
          - elasticfilesystem:TagResource
          - elasticfilesystem:UntagResource
          - elasticfilesystem:UpdateFileSystem
          - elasticfilesystem:DescribeMountTargetSecurityGroups
          - elasticfilesystem:ModifyMountTargetSecurityGroups
          - ecr:BatchCheckLayerAvailability
          - ecr:BatchGetImage
          - ecr:DescribeImageScanFindings
          - ecr:DescribeImages
          - ecr:DescribeRepositories
          - ecr:GetAuthorizationToken
          - ecr:GetDownloadUrlForLayer
          - ecr:GetLifecyclePolicy
          - ecr:GetLifecyclePolicyPreview
          - ecr:GetRepositoryPolicy
          - ecr:ListImages
          - ecr:ListTagsForResource
          - kms:DescribeKey
          - pricing:GetProducts
          Resource: "*"
        - Effect: Allow
          Action:
          - s3:GetObject
          - s3:ListBucket
          - s3:PutObject
          Resource:
          - !Sub 'arn:${AWS::Partition}:s3:::${S3BucketPrefix}-*'
          - !Sub 'arn:${AWS::Partition}:s3:::${S3BucketPrefix}-*/*'

Outputs:
  AccessKeyId:
    Description: "Access Key ID for the IAM user"
    Value: !Ref IAMAccessKey

  SecretAccessKey:
    Description: "Secret Access Key for the IAM user"
    Value: !GetAtt IAMAccessKey.SecretAccessKey
