apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./base
images:
  - name: public.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver
    newName: quay.io/platform9/aws-ebs-csi-driver
    newTag: 0.2.0 
