apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
data:
  # base64 encoded
  AccessKeyID: <BASE64 encoded AccessKeyID>
  SecretAccessKey: <BASE64 encoded SecretKey>
---
apiVersion: emp.pf9.io/v1alpha1
kind: AWSCredentials
metadata:
  name: aws-qa-creds
spec:
  # Reference to cloud provider credentials secret
  secretRef: aws-secret