apiVersion: emp.pf9.io/v1alpha1
kind: BaremetalPool
metadata:
  name: bm-test
spec:
  # Elastic Machine Pool object name to which baremetal pool is linked to.
  empName: emp-test
  # Baremetal Pool template.
  poolTemplate: 
    
    # AWS EC2 metal instance type/flavor
    instanceType: m5.metal

    ami:
      # For us-east-1 platform9 AMI ID - ami-07f258b65c6b2b925
      # For us-west-2 platform9 AMI ID - ami-013a0bf9c7a62047e
      # us-east-1
      id: ami-07f258b65c6b2b925
    
    # aws ssh key name
    sshKey: qa-emp
    region: us-east-1
    azs:
      - us-east-1a
      - us-east-1b
      - us-east-1c
    
    # Network configuration for baremetal pool
    network:
      # AWS VPC to consider to host baremetal machines.
      vpc:  
        id: vpc-0ee66d01a874305d5
      
      # List of subnets to be consider to host baremetal machines.
      subnets:
        # private subnet
        - id: subnet-012bbe7302b8c9b90
          isPrivate: true
          az: us-east-1a
        - id: subnet-0c1228e1c204e3a18
          isPrivate: true
          az: us-east-1b
        - id: subnet-012bb8d0d4aef8ea8
          isPrivate: true
          az: us-east-1c
        # public NAT subnet
        - id: subnet-0c0127713bbab8ad1
          isPrivate: false
          az: us-east-1a
        - id: subnet-03fc122ea4adb66f5
          isPrivate: false
          az: us-east-1b
        - id: subnet-0128ed1d460b8b761
          isPrivate: false
          az: us-east-1c
    # count of minimum machines/instances required in pool
    minMachines: 2

    # count of maximum machines/instances to be allowed to create in pool
    maxMachines: 10
