# A sample values.yaml file for users who want to install EMP related components on EKS cluster manually, using helm chart.
images: # images used by EMP components
  eks_vol_watcher: quay.io/platform9/eks-vol-watcher:<version>
  emp_pod_webhook: quay.io/platform9/emp-pod-webhook:<version>
  evm_autoscaler: quay.io/platform9/evm-autoscaler:<version>
  evm_vpc_cni: quay.io/platform9/evm-vpc-cni:<version>
  evm_vpc_cni_init: quay.io/platform9/evm-vpc-cni-init:<version>
manualInstallation: true # (*)
eksVolWatcher: # (*)
  secretName: <secret-name>
evmAutoScaler: # (*)
  endpoint: <redacted>
  token: <redacted>
baremetalInit: # (*)
  kubeconfig: <redacted>
  secretName: <secret-name>
  webhook:
    namespace: <namespace>
eksCNI: # (*)
  secretName: <secret-name>
applyEMPWebhook: true # this flag determines the installation of EMP Pod Webhook (default: true)
imagePullSecrets: '' # user needs to populate this field in case images are pushed to a custom registry (note the namespace in which secret is created should be same as specified above)

# (*) denotes that fields are auto-populated by EMP and should not be modified.