#!/bin/bash
set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

LOG_PREFIX="[$(date '+%Y-%m-%d %H:%M:%S')]"

log_info()  { echo -e "${GREEN}${LOG_PREFIX} [INFO]${NC}  $*"; }
log_warn()  { echo -e "${YELLOW}${LOG_PREFIX} [WARN]${NC}  $*"; }
log_error() { echo -e "${RED}${LOG_PREFIX} [ERROR]${NC} $*"; }
log_debug() { echo -e "${CYAN}${LOG_PREFIX} [DEBUG]${NC} $*"; }
log_step()  { echo -e "${BLUE}${LOG_PREFIX} [STEP]${NC}  $*"; }

update_log_prefix() { LOG_PREFIX="[$(date '+%Y-%m-%d %H:%M:%S')]"; }

usage() {
    echo "Usage: $0 <hosts_file>"
    echo ""
    echo "  <hosts_file>  File generated by list_missing_ha_hosts.sh"
    echo "                Format per line: host_id | hostname | cluster_name | responding | hypervisor_status | current_roles"
    echo ""
    echo "  Lines starting with '#' are skipped."
    exit 1
}

# Wrapper around curl that logs the request and checks for errors
do_curl() {
    local method="$1"
    local url="$2"
    local body="${3:-}"

    update_log_prefix
    log_debug "curl -s -X ${method} '${url}' -H 'X-Auth-Token: <REDACTED>' -H 'Content-Type: application/json'"

    local http_response
    if [[ -n "$body" ]]; then
        log_debug "Request body: ${body}"
        http_response=$(curl -s -w "\n%{http_code}" -X "${method}" "${url}" \
            -H "X-Auth-Token: ${TOKEN}" \
            -H "Content-Type: application/json" \
            -d "${body}")
    else
        http_response=$(curl -s -w "\n%{http_code}" -X "${method}" "${url}" \
            -H "X-Auth-Token: ${TOKEN}" \
            -H "Content-Type: application/json")
    fi

    local http_code
    http_code=$(echo "$http_response" | tail -n1)
    local response_body
    response_body=$(echo "$http_response" | sed '$d')

    log_debug "HTTP response code: ${http_code}"

    if [[ "$http_code" -lt 200 || "$http_code" -ge 300 ]]; then
        log_error "HTTP ${method} ${url} failed with status ${http_code}"
        log_error "Response body: ${response_body}"
        return 1
    fi

    echo "$response_body"
}

ask_yes_no() {
    local prompt="$1"
    while true; do
        read -rp "$(echo -e "${YELLOW}${prompt} (y/n): ${NC}")" answer
        case "$answer" in
            [Yy]|[Yy][Ee][Ss]) return 0 ;;
            [Nn]|[Nn][Oo]) return 1 ;;
            *) echo "Please answer y or n." ;;
        esac
    done
}

# ─── Validate arguments ─────────────────────────────────────────────────────

if [[ $# -lt 1 ]]; then
    usage
fi

HOSTS_FILE="$1"

if [[ ! -f "$HOSTS_FILE" ]]; then
    log_error "File not found: ${HOSTS_FILE}"
    exit 1
fi

echo -e "${BLUE}============================================${NC}"
echo -e "${BLUE}  Apply pf9-ha-slave Role${NC}"
echo -e "${BLUE}============================================${NC}"
echo ""

log_info "Reading hosts from: ${HOSTS_FILE}"

# ─── Gather inputs ──────────────────────────────────────────────────────────

read -rp "$(echo -e "${CYAN}Enter DU FQDN (e.g. my-du.platform9.io): ${NC}")" DU_FQDN
if [[ -z "$DU_FQDN" ]]; then
    log_error "DU FQDN cannot be empty. Exiting."
    exit 1
fi
log_info "DU FQDN set to: ${DU_FQDN}"

read -rsp "$(echo -e "${CYAN}Enter Auth Token: ${NC}")" TOKEN
echo ""
if [[ -z "$TOKEN" ]]; then
    log_error "Token cannot be empty. Exiting."
    exit 1
fi
log_info "Token received (hidden for security)."

BASE_URL="https://${DU_FQDN}"
log_info "Base URL: ${BASE_URL}"

# ─── Parse host file ────────────────────────────────────────────────────────

TOTAL=0
ELIGIBLE=0
SKIPPED=0
SUCCEEDED=0
FAILED=0

# Arrays to hold eligible and ineligible hosts for summary
declare -a ELIGIBLE_LINES=()
declare -a INELIGIBLE_LINES=()

log_step "Parsing host file and validating readiness ..."
echo ""

while IFS= read -r line; do
    # Skip comments and blank lines
    [[ "$line" =~ ^#.*$ ]] && continue
    [[ -z "${line// /}" ]] && continue

    TOTAL=$((TOTAL + 1))

    # Parse pipe-delimited fields
    HOST_ID=$(echo "$line" | awk -F'|' '{gsub(/^ +| +$/, "", $1); print $1}')
    HOSTNAME=$(echo "$line" | awk -F'|' '{gsub(/^ +| +$/, "", $2); print $2}')
    CLUSTER_NAME=$(echo "$line" | awk -F'|' '{gsub(/^ +| +$/, "", $3); print $3}')
    RESPONDING=$(echo "$line" | awk -F'|' '{gsub(/^ +| +$/, "", $4); print $4}')
    HV_STATUS=$(echo "$line" | awk -F'|' '{gsub(/^ +| +$/, "", $5); print $5}')
    ROLES=$(echo "$line" | awk -F'|' '{gsub(/^ +| +$/, "", $6); print $6}')

    log_debug "Parsed: id=${HOST_ID} hostname=${HOSTNAME} cluster=${CLUSTER_NAME} responding=${RESPONDING} pf9-ostackhost-neutron=${HV_STATUS} roles=${ROLES}"

    # Validate readiness: responding=true AND pf9-ostackhost-neutron=applied
    if [[ "$RESPONDING" != "true" || "$HV_STATUS" != "applied" ]]; then
        log_warn "INELIGIBLE: ${HOST_ID} (${HOSTNAME}) - responding=${RESPONDING}, pf9-ostackhost-neutron=${HV_STATUS}"
        INELIGIBLE_LINES+=("${HOST_ID} | ${HOSTNAME} | ${CLUSTER_NAME} | responding=${RESPONDING} | pf9-ostackhost-neutron=${HV_STATUS}")
        SKIPPED=$((SKIPPED + 1))
        continue
    fi

    ELIGIBLE_LINES+=("${HOST_ID} | ${HOSTNAME} | ${CLUSTER_NAME}")
    ELIGIBLE=$((ELIGIBLE + 1))

done < "$HOSTS_FILE"

# ─── Summary before proceeding ──────────────────────────────────────────────

echo ""
echo -e "${BLUE}────────────────────────────────────────────${NC}"
log_info "Parsed ${TOTAL} host(s) from file."
log_info "Eligible (responding=true, pf9-ostackhost-neutron=applied): ${ELIGIBLE}"
log_warn "Ineligible (skipped): ${SKIPPED}"

if [[ ${#INELIGIBLE_LINES[@]} -gt 0 ]]; then
    echo ""
    log_warn "Ineligible hosts:"
    for entry in "${INELIGIBLE_LINES[@]}"; do
        echo -e "  ${RED}- ${entry}${NC}"
    done
fi

if [[ "$ELIGIBLE" -eq 0 ]]; then
    log_error "No eligible hosts to apply role to. Exiting."
    exit 0
fi

echo ""
log_info "Eligible hosts:"
for entry in "${ELIGIBLE_LINES[@]}"; do
    echo -e "  ${GREEN}- ${entry}${NC}"
done

echo ""
if ! ask_yes_no "Apply 'pf9-ha-slave' role to these ${ELIGIBLE} host(s)?"; then
    log_info "Aborted by user."
    exit 0
fi

# ─── Apply role ──────────────────────────────────────────────────────────────

echo ""
log_step "Applying 'pf9-ha-slave' role ..."

while IFS= read -r line; do
    [[ "$line" =~ ^#.*$ ]] && continue
    [[ -z "${line// /}" ]] && continue

    HOST_ID=$(echo "$line" | awk -F'|' '{gsub(/^ +| +$/, "", $1); print $1}')
    HOSTNAME=$(echo "$line" | awk -F'|' '{gsub(/^ +| +$/, "", $2); print $2}')
    RESPONDING=$(echo "$line" | awk -F'|' '{gsub(/^ +| +$/, "", $4); print $4}')
    HV_STATUS=$(echo "$line" | awk -F'|' '{gsub(/^ +| +$/, "", $5); print $5}')

    # Skip ineligible hosts again
    if [[ "$RESPONDING" != "true" || "$HV_STATUS" != "applied" ]]; then
        continue
    fi

    PUT_URL="${BASE_URL}/resmgr/v1/hosts/${HOST_ID}/roles/pf9-ha-slave"
    log_step "PUT ${PUT_URL} for host ${HOST_ID} (${HOSTNAME}) ..."

    if RESULT=$(do_curl PUT "$PUT_URL" "{}"); then
        log_info "SUCCESS: Applied 'pf9-ha-slave' to ${HOST_ID} (${HOSTNAME})."
        log_debug "Response: ${RESULT}"
        SUCCEEDED=$((SUCCEEDED + 1))
    else
        log_error "FAILED: Could not apply 'pf9-ha-slave' to ${HOST_ID} (${HOSTNAME}). Continuing."
        FAILED=$((FAILED + 1))
    fi

done < "$HOSTS_FILE"

# ─── Final summary ──────────────────────────────────────────────────────────

echo ""
echo -e "${BLUE}────────────────────────────────────────────${NC}"
log_info "Final Summary:"
log_info "  Total hosts in file : ${TOTAL}"
log_info "  Skipped (ineligible): ${SKIPPED}"
log_info "  Attempted           : ${ELIGIBLE}"
log_info "  Succeeded           : ${SUCCEEDED}"
log_info "  Failed              : ${FAILED}"

echo ""
echo -e "${GREEN}============================================${NC}"
echo -e "${GREEN}  Script completed.${NC}"
echo -e "${GREEN}============================================${NC}"
